name: Build and Release

on:
  pull_request: 
    branches: [main]
  push:
    branches: [main]

jobs: 
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cehckout
      uses: actions/checkout@v4
    
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --add-data "src/resources/images/*:images/" --add-data "src/resources/*:./" src/main.py 

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: dist/