name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 只有 push tag（如 v1.0.0）时触发

jobs: 
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cehckout
      uses: actions/checkout@v4
    
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        pwd
        ls
        pyinstaller --onefile --add-data "src/resources/images/*:images/" --add-data "src/resources/*:./" src/main.py 

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}